pipeline:
  name: disney test
  identifier: disney_test
  projectIdentifier: vbtestsanity
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: eoin
        repoName: demo-macos
        build: <+input>
  stages:
    - stage:
        name: run
        identifier: run
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run xcode
                  identifier: Run_xcode
                  spec:
                    shell: Sh
                    command: xcodebuild
  delegateSelectors:
    - eoin-delegate
