pipeline:
  name: disney test
  identifier: disney_test
  projectIdentifier: vbtestsanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: run
        identifier: run
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: MacOS
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: clone
                  identifier: clone
                  spec:
                    shell: Sh
                    command: |-
                      mkdir -p ~/harness
                      cd ~/harness
                      git clone https://github.com/eoinmcafee00/demo-macos.git
                      cd demo-macos
                      git pull
              - step:
                  type: Run
                  name: echo
                  identifier: echo
                  spec:
                    shell: Sh
                    command: echo hey
              - step:
                  type: Run
                  name: Run xcode
                  identifier: Run_xcode
                  spec:
                    shell: Sh
                    command: |-
                      cd ~/harness/demo-macos
                      xcodebuild
                      exit 0
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - tests.xml
  delegateSelectors:
    - eoin-delegate
